spring.application.name=recouvChatbot_rag
#spring.ai.ollama.chat.model=llama3.2
#spring.ai.ollama.embedding.options.model=mxbai-embed-large
#spring.ai.ollama.base-url=http://localhost:11434
server.port=8082
spring.ai.openai.api-key=REDACTED_LEAKED_OPENAI_KEY
spring.ai.openai.chat.options.model=gpt-4o
spring.ai.openai.embedding.options.model=text-embedding-3-small

#spring.datasource.url=jdbc:mysql://localhost:3306/recouvdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=Maksaad
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Disable database

spring.docker.compose.enabled=false
#spring.docker.compose.lifecycle-management=start_only

spring.datasource.url=jdbc:postgresql://localhost:5432/recouvrag_db
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=1536